# Generated by Django 3.0.8 on 2020-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('team', models.CharField(max_length=256)),
                ('salary', models.CharField(max_length=1024)),
                ('war', models.CharField(max_length=256)),
            ],
        ),
    ]
